### PR TITLE
repack_boot.sh: e850-96: Adding earlycon for early printk from kernel

### PR DESCRIPTION
**Pull request by nareshkamboju**

### CODE REVIEW

**Comment by bhcopeland** [comment]
Can you add target device to the commit message?

**Comment by nareshkamboju** [comment]
> Can you add target device to the commit message?

Thanks for the finding.
Now it is resolved.

**Comment by roxell** [comment]
amazing, can you please add it console_cmdline line 110 in the same file please.
also remove it from line 131 ?

**Comment by nareshkamboju** [comment]
> console_cmdline

Hi Anders,

I have made the changes as per your review comments.
Please review this PR.

**Pull request merged**
